#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

mvn clean package install
